#!/bin/bash

# Copyright 2024 Cyanic
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME='Alacritty Dropdown'
CMD='alacritty -T "$ALACRITTY_DROPDOWN_WINDOW_NAME" \
    --config-file "$HOME/.alacritty-dropdown.yml"'
LOCKFILE="/tmp/alacritty-dropdown-$UID.lock"
WIDFILE="/tmp/alacritty-dropdown-$UID.wid"

function show() {
    WFWID=$(cat "$WIDFILE" 2>/dev/null)
    xdotool windowmap "$WFWID"
}
function hide() {
    echo "$1" > "$WIDFILE"
    xdotool windowunmap "$1"
}
function focused() {
    xprop -id "$1" | grep _NET_WM_STATE_FOCUSED >/dev/null
}
function focus() {
    xdotool set_desktop_for_window "$1" "$(xdotool get_desktop)"
    wmctrl -i -a "$1"
}

WID=$(wmctrl -l | grep -Po '^\S+(?=.*?'"$NAME"'$)')
if [ -z "$WID" ]; then
    export ALACRITTY_DROPDOWN_WINDOW_NAME="$NAME"
    flock -no "$LOCKFILE" -c "$CMD" || show
    exit $?
fi

if focused "$WID"; then
    hide "$WID"
else
    focus "$WID"
fi
