#!/bin/bash

# Copyright 2026 Cyanic
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME='Alacritty Dropdown'
WIDTH='100%'
HEIGHT='75%'

CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
CONFIG_FILE="$CONFIG_HOME/alacritty/alacritty-dropdown.toml"

# Fall back to deprecated config file locations
if [[ ! -f "$CONFIG_FILE" ]]; then
    CONFIG_FILE="$HOME/.alacritty-dropdown.toml"

    CONFIG_FILE_YAML="$HOME/.alacritty-dropdown.yml"
    if [[ ! -f "$CONFIG_FILE" && -f "$CONFIG_FILE_YAML" ]]; then
        CONFIG_FILE="$CONFIG_FILE_YAML"
    fi
fi

CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
CACHE_DIR="$CACHE_HOME/alacritty-dropdown"
WID_FILE="$CACHE_DIR/wid"

show() {
    WFWID=$(cat "$WID_FILE" 2>/dev/null)
    xdotool windowmap "$WFWID"
}

hide() {
    echo "$1" > "$WID_FILE"
    xdotool windowunmap "$1"
}

focused() {
    xprop -id "$1" | grep _NET_WM_STATE_FOCUSED >/dev/null
}

focus() {
    xdotool set_desktop_for_window "$1" "$(xdotool get_desktop)"
    wmctrl -i -a "$1"
}

getwid() {
    wmctrl -l | grep -Po '^\S+(?=.*?'"$NAME"'$)'
}

if [[ "$1" == resize ]]; then
    while [[ -z "$WID" ]]; do
        WID=$(getwid)
    done
    exec xdotool windowsize "$WID" "$WIDTH" "$HEIGHT"
fi

if [[ "$1" == run ]]; then
    (timeout 10s "$0" resize &)
    exec alacritty -T "${NAME}" --config-file "${CONFIG_FILE}"
fi

WID="$(getwid)"
if [[ -z "$WID" ]]; then
    mkdir -p "$CACHE_DIR"
    flock -no "$CACHE_DIR/lock" "$0" run || show
    exit $?
fi

if focused "$WID"; then
    hide "$WID"
else
    focus "$WID"
fi
